CC = gcc
CFLAGS = -Wall -pthread -g
LDFLAGS = -lrt -pthread

TARGETS = multi_process_demo

all: $(TARGETS)

multi_process_demo: multi_process_demo.c shared_memory.h backend_process.h
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

clean:
	rm -f $(TARGETS)

.PHONY: all clean
